version: '2'

services:
  database:
    container_name: pjqtr-mysql
    image: mysql:5.6
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - "./data/db:/var/lib/mysql:rw"
    environment:
      - "MYSQL_DATABASE=projeqtor-test"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=mysql"
      - "MYSQL_ROOT_PASSWORD=mysql"
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: pjqtr-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8181:80"
    environment:
      - "MYSQL_USERNAME=root"
      - "MYSQL_PASSWORD=password"
    links:
      - database:db
    depends_on:
      - database

  projeqtor:
    image: lavoweb/php-5.6
    container_name: pjqtr-projeqtor
    volumes:
        - "./conf/php.ini:/usr/local/etc/php/php.ini:ro"
        - "./data/www/projeqtor:/var/www/html:rw"
    ports:
      - "80:80"
    links:
      - database:mysql
    depends_on:
      - database

